#!/usr/bin/env python3
"""Production Store Release workflow suite (issue #98). Run from the repo root:

    pixi run test                    # or: python3 tests/release-workflow/run_tests.py

The ticket's acceptance criteria are behaviours of the Snakemake DAG, so this
suite drives the real `workflow/Snakefile` against the tiny checked-in
FinnGen-shaped fixture release (`fixtures/r13-fixture/`, regenerated by
`fixtures/generate_r13_fixture.py`) and asserts what the operator sees:

* the one `pixi run release --configfile <build.yaml>` command builds a genuine
  Store end to end, whose `overview.html` is the regenerated one and whose
  `validation.yaml` records a passing `opengwasdb validate`;
* every phase writes a completion record that binds the fixed inputs, the
  `opengwasdb` revision and the effective arguments;
* killing the run before the build, and leaving a partial Store behind, both
  resume rather than treating the partial Store as complete;
* a completed build rerun is a no-op;
* editing `build.yaml`, `analyses.tsv`, a source file, or a declared Reference
  Resource descriptor invalidates the affected phases;
* a release whose `analyses.tsv` names its source column `file_name` (rather
  than `source_file`) still resolves and builds;
* the Snakefile itself is wiring only;
* the rho and Reference-Completion branches are refused, not silently skipped.

The fixture is copied into a temporary directory per scenario and its
`artifacts.artifact_root` repointed there, so the suite leaves no Store or work
files in the repository.
"""
from __future__ import annotations

import csv
import gzip
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE = REPO_ROOT / "tests" / "release-workflow" / "fixtures" / "r13-fixture"
SNAKEFILE = REPO_ROOT / "workflow" / "Snakefile"
PHASE_RUNNER = REPO_ROOT / "workflow" / "phase.py"
SNAKEMAKE = shutil.which("snakemake")

sys.path.insert(0, str(REPO_ROOT))
from resources.lib.release_yaml import read_tsv  # noqa: E402

#: The pinned `opengwasdb` revision, read from pixi.toml rather than hardcoded
#: so a pin bump does not silently invalidate the completion-record assertion.
OPENGWASDB_REVISION = (
    tomllib.loads((REPO_ROOT / "pixi.toml").read_text(encoding="utf-8"))["feature"]
    ["store-build"]["pypi-dependencies"]["opengwasdb"]["rev"]
)

#: Fixture Analysis ids, in analyses.tsv order.
FIXTURE_ANALYSES = (
    "finngen-r13-BMI_FIXTURE",
    "finngen-r13-HEIGHT_FIXTURE",
    "finngen-r13-RX_STATIN_FIXTURE",
)

#: Fixture union variant count (4 BMI + 2 new HEIGHT + 2 new RX_STATIN).
FIXTURE_VARIANTS = 8

PHASES = (
    "validate_fixed_inputs",
    "resolve_analysis_metadata",
    "build_observed_store",
    "regenerate_observed_overview",
    "validate_observed_release",
)

n_checks = 0


def check(condition: bool, message: str) -> None:
    global n_checks
    n_checks += 1
    if not condition:
        raise AssertionError(message)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


@dataclass(frozen=True)
class Fixture:
    """One temporary copy of the fixture release, wired to a temporary artifact root."""

    release_dir: Path
    work_dir: Path
    store_dir: Path

    @property
    def build_yaml(self) -> Path:
        return self.release_dir / "build.yaml"

    @property
    def analyses(self) -> Path:
        return self.release_dir / "analyses.tsv"

    @property
    def sources(self) -> list[Path]:
        return sorted((self.release_dir / "source").glob("*.gz"))

    def completion(self, phase: str) -> Path:
        return self.work_dir / "completions" / f"{phase}.json"

    def record(self, phase: str) -> dict:
        return json.loads(self.completion(phase).read_text(encoding="utf-8"))

    def validation(self) -> dict:
        return _read_validation(self.release_dir / "validation.yaml")

    def sidecar(self, name: str) -> Path:
        return self.release_dir / "sidecars" / name


def _read_validation(path: Path) -> dict:
    """Read the flat `validation.yaml` fields this suite asserts on."""
    fields: dict[str, str] = {}
    checks: dict[str, str] = {}
    in_checks = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line == "checks:":
            in_checks = True
            continue
        if in_checks and line and not line.startswith(" "):
            in_checks = False
        if in_checks and line.startswith("  "):
            key, _, value = line.strip().partition(": ")
            checks[key] = value
        elif line and not line.startswith(" ") and ": " in line:
            key, _, value = line.partition(": ")
            fields[key] = value
    fields["checks"] = checks
    return fields


def prepare(temp_root: Path, name: str) -> Fixture:
    """Copy the fixture release and point its artifact root at the temp directory."""
    scenario = temp_root / name
    shutil.rmtree(scenario, ignore_errors=True)
    release_dir = scenario / "release"
    shutil.copytree(FIXTURE, release_dir)
    artifacts = scenario / "artifacts"
    build_yaml = release_dir / "build.yaml"
    text = build_yaml.read_text(encoding="utf-8")
    assert "artifact_root: .release-work" in text, "fixture build.yaml no longer declares the repo-local root"
    build_yaml.write_text(text.replace("artifact_root: .release-work", f"artifact_root: {artifacts}"), encoding="utf-8")
    work_dir = artifacts / "finngen-r13" / "releases" / "r13-fixture" / "work"
    store_dir = work_dir.parent / "store.opengwasdb"
    return Fixture(release_dir=release_dir, work_dir=work_dir, store_dir=store_dir)


def snakemake(
    fixture: Fixture,
    *,
    until: str | None = None,
    force: str | None = None,
    dry_run: bool = False,
) -> subprocess.CompletedProcess:
    command = [
        str(SNAKEMAKE),
        "--snakefile", str(SNAKEFILE),
        "--configfile", str(fixture.build_yaml),
        "--cores", "1",
        "--printshellcmds",
    ]
    if until:
        command += ["--until", until]
    if force:
        command += ["--forcerun", force]
    if dry_run:
        command += ["--dry-run"]
    return subprocess.run(command, cwd=REPO_ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)


def planned_rules(result: subprocess.CompletedProcess) -> set[str]:
    """The rules a dry run would execute, from Snakemake's job-stats table."""
    assert_success(result, "dry run")
    return {match.group(1) for match in re.finditer(r"^(\S+)\s+\d+$", result.stdout, re.M)}


def run_phase_runner(fixture: Fixture, phase: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(PHASE_RUNNER), "--phase", phase,
         "--config", str(fixture.build_yaml), "--repo-root", str(REPO_ROOT)],
        cwd=REPO_ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )


def store_analysis_ids(fixture: Fixture) -> list[str]:
    return [row["analysis_id"] for row in read_tsv(fixture.store_dir / "analyses.tsv")]


def rewrite_analyses(fixture: Fixture, mutate) -> None:
    fieldnames, rows = _rows(fixture.analyses)
    for row in rows:
        mutate(row)
    with fixture.analyses.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t", lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def _rows(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        return list(reader.fieldnames or []), list(reader)


def append_variant(path: Path, row: list[str]) -> None:
    """Append one FinnGen-shaped row, keeping the gzip header timestamp-free."""
    with gzip.open(path, "rt", newline="", encoding="utf-8") as handle:
        existing = list(csv.reader(handle, delimiter="\t"))
    assert existing[0] == ["#chrom", "pos", "ref", "alt", "beta", "sebeta", "af_alt", "rsids"]
    existing.append(row)
    with path.open("wb") as raw:
        with gzip.GzipFile(fileobj=raw, mode="wb", mtime=0) as compressed:
            with io.TextIOWrapper(compressed, encoding="utf-8", newline="") as text:
                writer = csv.writer(text, delimiter="\t", lineterminator="\n")
                for line in existing:
                    writer.writerow(line)


def assert_success(result: subprocess.CompletedProcess, label: str) -> None:
    if result.returncode != 0:
        raise AssertionError(f"{label} failed (exit {result.returncode}):\n{result.stdout[-4000:]}")


# ---------------------------------------------------------------------------
# Scenarios
# ---------------------------------------------------------------------------


def test_scratch_build(temp_root: Path) -> Fixture:
    """One command builds a genuine Store, overview, and validation result."""
    fixture = prepare(temp_root, "scratch")
    result = snakemake(fixture)
    assert_success(result, "scratch build")

    check(fixture.store_dir.is_dir(), "the fixture Store was not built")
    manifest = json.loads((fixture.store_dir / "manifest.json").read_text(encoding="utf-8"))
    check(manifest["store_id"] == "finngen-r13", f"unexpected store_id {manifest['store_id']!r}")
    check(manifest["release_id"] == "r13-fixture", f"unexpected release_id {manifest['release_id']!r}")
    check(manifest["format_version"] == "1.0", f"unexpected store format {manifest['format_version']!r}")
    check(store_analysis_ids(fixture) == list(FIXTURE_ANALYSES), "built Store carries the wrong Analyses")
    check((fixture.store_dir / "data.zarr").is_dir(), "built Store has no data.zarr")

    overview = (fixture.store_dir / "overview.html").read_text(encoding="utf-8")
    check("<html>" in overview, "overview.html is not HTML")
    for analysis_id in FIXTURE_ANALYSES:
        check(analysis_id in overview, f"overview.html omits {analysis_id}")

    validation = fixture.validation()
    check(validation["status"] == "passed", f"validation.yaml status is {validation['status']!r}")
    check(validation["checks"].get("store") == "passed", "the CLI store check did not pass")
    check(validation["checks"].get("files") == "passed", "the build file check did not pass")
    check(validation["checks"].get("schema") == "passed", "the schema check did not pass")

    for phase in PHASES:
        check(fixture.completion(phase).is_file(), f"no completion record for {phase}")

    report = read_tsv(fixture.sidecar("build-report.tsv"))[0]
    check(int(report["n_analyses"]) == len(FIXTURE_ANALYSES), "build report n_analyses mismatch")
    check(int(report["n_variants"]) == FIXTURE_VARIANTS, "build report n_variants mismatch")
    check(report["status"] == "passed", "build report is not passed")
    check("/store.opengwasdb.partial " in report["command"] + " ", "build did not build into a .partial sibling")

    inputs = json.loads(fixture.sidecar("input-validation.json").read_text(encoding="utf-8"))
    check(inputs["status"] == "passed", "input-validation.json is not passed")
    check(inputs["analysis_count"] == len(FIXTURE_ANALYSES), "input-validation analysis_count mismatch")
    check(inputs["checksums_verified"] is True, "input validation did not verify checksums")

    resolution = read_tsv(fixture.sidecar("metadata-resolution.tsv"))
    check(len(resolution) == len(FIXTURE_ANALYSES), "metadata-resolution.tsv row count mismatch")
    check(all(row["ancestry_status"] == "passthrough" for row in resolution), "resolve phase did more than passthrough")
    return fixture


def test_completion_records_bind_inputs(fixture: Fixture) -> None:
    """Every record binds the fixed inputs, the revision, and the effective arguments."""
    record = fixture.record("build_observed_store")
    check(record["phase"] == "build_observed_store", "record names the wrong phase")
    check(record["store_family_id"] == "finngen-r13", "record names the wrong Store Family")
    check(record["family_release_id"] == "r13-fixture", "record names the wrong release")

    bound = record["inputs"]
    check(bound[str(fixture.build_yaml)] == sha256(fixture.build_yaml), "record does not bind build.yaml")
    check(bound[str(fixture.analyses)] == sha256(fixture.analyses), "record does not bind analyses.tsv")
    for source in fixture.sources:
        check(bound[str(source)] == sha256(source), f"record does not bind {source.name}")
    descriptor = REPO_ROOT / "reference-resources" / "qc-panel-hg38" / "resource.yaml"
    check(bound[str(descriptor)] == sha256(descriptor), "record does not bind the declared Reference Resource descriptor")

    check(record["opengwasdb"]["revision"] == OPENGWASDB_REVISION, "record binds the wrong opengwasdb revision")
    check(record["opengwasdb"]["version"], "record binds no opengwasdb version")
    check("--store-id" in record["command"] and "finngen-r13" in record["command"], "effective arguments are not recorded")
    check(record["command"][1] == "build-dense-vcf", f"record names command {record['command'][1]!r}")
    check(str(fixture.store_dir / "manifest.json") in record["outputs"], "record does not name the Store envelope output")
    check(record["completed_at"].endswith("+00:00"), "record has no UTC completion time")
    check(record["validation"]["status"] == "passed", "record does not carry the read-back result")
    check(record["input_fingerprint"], "record has no input fingerprint")

    overview = fixture.record("regenerate_observed_overview")
    check(overview["command"][1] == "regenerate-overview", "overview phase did not call regenerate-overview")
    check(str(fixture.store_dir / "overview.html") in overview["outputs"], "overview record does not name overview.html")
    check(overview["validation"]["overview_sha256"] == sha256(fixture.store_dir / "overview.html"),
          "overview record does not bind the regenerated page")

    validate = fixture.record("validate_observed_release")
    check(validate["command"][1] == "validate", "validate phase did not call opengwasdb validate")
    check(str(fixture.release_dir / "validation.yaml") in validate["outputs"], "validate record does not name validation.yaml")


def test_reference_descriptor_invalidates_phases(fixture: Fixture) -> None:
    """Editing a declared Reference Resource descriptor invalidates the phases that bind it.

    The descriptor is a repository file (not part of the fixture copy), so the
    edit is a temporary content change restored in a `finally`. The dry run only
    plans -- it never executes a phase -- so the modified descriptor is never
    validated, and restoring it makes the DAG a no-op again.
    """
    descriptor = REPO_ROOT / "reference-resources" / "qc-panel-hg38" / "resource.yaml"
    original = descriptor.read_bytes()
    stat = descriptor.stat()
    try:
        descriptor.write_bytes(original + b"# workflow-invalidation probe\n")
        planned = planned_rules(snakemake(fixture, dry_run=True))
        check("validate_fixed_inputs" in planned,
              "editing a declared Reference Resource descriptor did not invalidate validate_fixed_inputs")
        check("resolve_analysis_metadata" in planned,
              "editing a declared Reference Resource descriptor did not invalidate resolve_analysis_metadata")
    finally:
        descriptor.write_bytes(original)
        os.utime(descriptor, (stat.st_atime, stat.st_mtime))
    check(descriptor.read_bytes() == original, "the Reference Resource descriptor was not restored")
    check("validate_fixed_inputs" not in planned_rules(snakemake(fixture, dry_run=True)),
          "the restored descriptor still invalidates validate_fixed_inputs")


def test_completed_rerun_is_noop(fixture: Fixture) -> None:
    """Rerunning a fully completed build re-executes no phase."""
    before = {phase: sha256(fixture.completion(phase)) for phase in PHASES}
    result = snakemake(fixture)
    assert_success(result, "no-op rerun")
    check("Nothing to be done" in result.stdout, "the DAG did not report itself up to date")
    check(all(sha256(fixture.completion(phase)) == digest for phase, digest in before.items()),
          "a rerun rewrote a completion record")


def test_interrupted_run_resumes(temp_root: Path) -> Fixture:
    """Stopping before the build leaves no Store and resumes without redoing resolve."""
    fixture = prepare(temp_root, "interrupted")
    result = snakemake(fixture, until="resolve_analysis_metadata")
    assert_success(result, "interrupted run")
    check(fixture.completion("resolve_analysis_metadata").is_file(), "resolve did not complete")
    check(not fixture.completion("build_observed_store").exists(), "build completed despite --until resolve")
    check(not fixture.store_dir.exists(), "a Store exists before the build phase ran")

    resolve_hash = sha256(fixture.completion("resolve_analysis_metadata"))
    result = snakemake(fixture)
    assert_success(result, "resume run")
    check(fixture.completion("build_observed_store").is_file(), "resume did not build the Store")
    check(fixture.validation()["status"] == "passed", "resumed release did not validate")
    check(sha256(fixture.completion("resolve_analysis_metadata")) == resolve_hash,
          "resume re-ran the already-complete resolve phase")
    return fixture


def test_partial_store_cannot_masquerade(fixture: Fixture) -> None:
    """A partial Store with no completion record is rebuilt, not trusted.

    This is what an interrupted build leaves behind: the completed phases keep
    their records, the build and everything after it have none, and the Store
    path holds whatever the killed process had written. The rerun must descend
    into the missing phases and replace the partial Store.
    """
    resolve_hash = sha256(fixture.completion("resolve_analysis_metadata"))

    for phase in ("build_observed_store", "regenerate_observed_overview", "validate_observed_release"):
        fixture.completion(phase).unlink()
    (fixture.store_dir / "manifest.json").unlink()
    (fixture.store_dir / "PARTIAL").write_text("interrupted build\n", encoding="utf-8")

    result = snakemake(fixture)
    assert_success(result, "partial-store rerun")
    check(not (fixture.store_dir / "PARTIAL").exists(), "the partial Store survived the rerun")
    check((fixture.store_dir / "manifest.json").is_file(), "the rerun did not rebuild the Store envelope")
    check(store_analysis_ids(fixture) == list(FIXTURE_ANALYSES), "the rebuilt Store carries the wrong Analyses")
    check(fixture.validation()["status"] == "passed", "the rebuilt Store did not validate")
    check(sha256(fixture.completion("resolve_analysis_metadata")) == resolve_hash,
          "the rerun re-ran the already-complete resolve phase")
    check(not fixture.store_dir.with_name(fixture.store_dir.name + ".partial").exists(),
          "the build left its .partial sibling behind")


def test_edits_invalidate_and_flow_through(fixture: Fixture) -> None:
    """Editing build.yaml, analyses.tsv, or a source file invalidates the affected phases.

    Each edit is checked with a dry run -- the DAG Snakemake would execute --
    and then one real run proves all three edits actually reach the Store.
    """
    before_build = sha256(fixture.completion("build_observed_store"))

    fixture.build_yaml.write_text(
        fixture.build_yaml.read_text(encoding="utf-8").replace("n-workers: 1", "n-workers: 2"),
        encoding="utf-8",
    )
    check("build_observed_store" in planned_rules(snakemake(fixture, dry_run=True)),
          "editing build.yaml did not invalidate the build phase")

    rewrite_analyses(fixture, lambda row: row.update(
        {"analysis_label": "Edited body mass index"} if row["analysis_id"] == FIXTURE_ANALYSES[0] else {}
    ))
    check("resolve_analysis_metadata" in planned_rules(snakemake(fixture, dry_run=True)),
          "editing analyses.tsv did not invalidate the resolve phase")

    edited_source = fixture.release_dir / "source" / "finngen_R13_BMI_FIXTURE.gz"
    append_variant(edited_source, ["8", "9000000", "A", "C", "0.04", "0.02", "0.37", "rs9"])
    new_checksum = sha256(edited_source)
    rewrite_analyses(fixture, lambda row: row.update(
        {"checksum": new_checksum} if row["analysis_id"] == FIXTURE_ANALYSES[0] else {}
    ))
    check("build_observed_store" in planned_rules(snakemake(fixture, dry_run=True)),
          "editing a source file did not invalidate the build phase")

    result = snakemake(fixture)
    assert_success(result, "edited inputs rerun")
    check(sha256(fixture.completion("build_observed_store")) != before_build,
          "the edited inputs did not re-run the build")
    labels = {row["analysis_id"]: row["analysis_label"] for row in read_tsv(fixture.store_dir / "analyses.tsv")}
    check(labels[FIXTURE_ANALYSES[0]] == "Edited body mass index", "the edited label did not reach the Store")
    report = read_tsv(fixture.sidecar("build-report.tsv"))[0]
    check(int(report["n_variants"]) == FIXTURE_VARIANTS + 1, "the new source variant did not reach the Store")
    command = fixture.record("build_observed_store")["command"]
    check("--n-workers" in command and "2" in command, "the edited build argument did not reach the CLI")
    check(fixture.validation()["status"] == "passed", "the release did not validate after the edits")


def test_file_name_source_column(temp_root: Path) -> None:
    """analyses.tsv may name its source column `file_name` instead of `source_file`.

    `resources/lib/release_plan.py` and `workflow/model.py` both accept either
    name. The resolve phase must resolve `file_name` the same way, or the shared
    builder manifest points at the source directory rather than each file.
    """
    fixture = prepare(temp_root, "file-name-column")
    lines = fixture.analyses.read_text(encoding="utf-8").splitlines()
    header = lines[0].split("\t")
    header[header.index("source_file")] = "file_name"
    lines[0] = "\t".join(header)
    fixture.analyses.write_text("\n".join(lines) + "\n", encoding="utf-8")

    result = snakemake(fixture)
    assert_success(result, "file_name source column build")
    check(store_analysis_ids(fixture) == list(FIXTURE_ANALYSES),
          "the file_name-column release built the wrong Analyses")
    manifest = read_tsv(fixture.work_dir / "builder-manifest.tsv")
    check(len(manifest) == len(FIXTURE_ANALYSES), "builder manifest row count mismatch")
    for row in manifest:
        file_path = Path(row["file_path"])
        check(file_path.is_absolute(), f"builder manifest file_path {row['file_path']!r} is not absolute")
        check(file_path.is_file(), f"builder manifest file_path {row['file_path']!r} is not a source file")


def test_snakefile_is_wiring_only() -> None:
    """The Snakefile names no Store Family, no column, and no Store Layout."""
    text = SNAKEFILE.read_text(encoding="utf-8")
    forbidden = (
        "finngen", "analysis_id", "source_file", "analysis_label", "source_genome_build",
        "source_reader_capability", "trait_id", "trait_name", "file_path", "stored_effect_scale",
        "original_sd_method", "sample_size",
        "dense", "hybrid", "ragged",
    )
    for token in forbidden:
        check(token not in text, f"the Snakefile contains {token!r}")
    check("phase.py" in text, "the Snakefile does not delegate to the phase runner")


def test_deferred_branches_are_refused(temp_root: Path) -> None:
    """rho and Reference Completion are refused rather than silently skipped."""
    fixture = prepare(temp_root, "deferred")
    original = fixture.build_yaml.read_text(encoding="utf-8")
    for name, before, after in (
        (
            "rho",
            "rho:\n  enabled: false",
            "rho:\n  enabled: true\n  window_bp: 1000000",
        ),
        (
            "reference_completion",
            "reference_completion:\n  enabled: false",
            "reference_completion:\n  enabled: true\n"
            "  family_release_id: r13-fixture-reference-completed\n  command: complete-dense",
        ),
    ):
        check(before in original, f"fixture build.yaml has no {name} block to edit")
        fixture.build_yaml.write_text(original.replace(before, after), encoding="utf-8")
        result = run_phase_runner(fixture, "validate_fixed_inputs")
        check(result.returncode != 0, f"{name} was not refused")
        check("#100" in result.stdout, f"{name} refusal does not name issue #100")
    fixture.build_yaml.write_text(original, encoding="utf-8")


def test_hand_written_overview_is_replaced(fixture: Fixture) -> None:
    """overview.html is generated from Store data, not hand-written."""
    overview = fixture.store_dir / "overview.html"
    expected = overview.read_bytes()
    before = sha256(fixture.completion("validate_observed_release"))
    overview.write_text("hand-written overview\n", encoding="utf-8")

    result = snakemake(fixture, force="regenerate_observed_overview")
    assert_success(result, "overview regeneration")
    check(overview.read_bytes() == expected, "the hand-written overview was not replaced by the regenerated one")
    check(fixture.record("regenerate_observed_overview")["command"][1] == "regenerate-overview",
          "the overview was not produced by regenerate-overview")
    check(sha256(fixture.completion("validate_observed_release")) != before,
          "validation did not re-run downstream of the regeneration")


def main() -> int:
    if SNAKEMAKE is None:
        print(
            "snakemake is not on PATH; run this suite via `pixi run test` (or --environment workflow)",
            file=sys.stderr,
        )
        return 2
    with tempfile.TemporaryDirectory(prefix="release-workflow-") as temp:
        temp_root = Path(temp)
        fixture = test_scratch_build(temp_root)
        test_completion_records_bind_inputs(fixture)
        test_reference_descriptor_invalidates_phases(fixture)
        test_completed_rerun_is_noop(fixture)
        test_hand_written_overview_is_replaced(fixture)
        test_edits_invalidate_and_flow_through(fixture)
        test_file_name_source_column(temp_root)
        test_snakefile_is_wiring_only()
        test_deferred_branches_are_refused(temp_root)
        test_partial_store_cannot_masquerade(test_interrupted_run_resumes(temp_root))
    print(f"release-workflow: {n_checks} checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
