#!/usr/bin/env python3
"""Production Store Release workflow suite (issue #98; real resolution #99).

    pixi run test                    # or: python3 tests/release-workflow/run_tests.py

The ticket's acceptance criteria are behaviours of the Snakemake DAG, so this
suite drives the real `workflow/Snakefile` against the tiny checked-in
FinnGen-shaped fixture release (`fixtures/r13-fixture/`, regenerated by
`fixtures/generate_r13_fixture.py`) and asserts what the operator sees:

* the one `pixi run release --configfile <build.yaml>` command builds a genuine
  Store end to end, whose `overview.html` is the regenerated one and whose
  `validation.yaml` records the `opengwasdb validate` result;
* issue #99: resolution derives Assigned Ancestry, proportions, and phenotype SD
  into `work/analyses.resolved.tsv` and the built Store, leaves the committed
  `analyses.tsv` byte-identical, names every derived Analysis in
  `sidecars/metadata-resolution.tsv`, records the failed effect-scale check in
  `validation.yaml`, lands the release as `built` rather than `validated`, and
  binds the ancestry reference panel into the completion record;
* a `build.yaml` `effect_scale_validation.block_on_failure` escalates that
  failure to blocking;
* every phase writes a completion record that binds the fixed inputs, the
  `opengwasdb` revision and the effective arguments;
* killing the run before the build, and leaving a partial Store behind, both
  resume rather than treating the partial Store as complete;
* a completed build rerun is a no-op;
* editing `build.yaml`, `analyses.tsv`, a source file, or a declared Reference
  Resource invalidates the affected phases;
* a release whose `analyses.tsv` names its source column `file_name` (rather
  than `source_file`) still resolves and builds;
* the Snakefile itself is wiring only;
* with rho enabled the observed Store gains `data.zarr/rho` and its
  `overview.html` is regenerated *after* it, with the Rho tab present;
* with rho disabled no rho group, record, or tab exists;
* rho on a non-Dense layout is refused at input validation, before any Store
  work;
* with Reference Completion enabled a lineage-linked child Store Release is
  registered and a separate child Store is built, leaving the observed parent
  byte-unchanged;
* the child runs rho, overview regeneration, and validation in the same order
  as the observed release;
* an interrupted completion resumes rather than treating the partial child as
  complete, and a partial child Store is rebuilt rather than trusted.

The fixture is copied into a temporary directory per scenario and its
`artifacts.artifact_root` repointed there, so the suite leaves no Store or work
files in the repository.
"""
from __future__ import annotations

import csv
import gzip
import hashlib
import io
import json
import os
import re
import shutil
import signal
import subprocess
import sys
import tempfile
import time
import tomllib
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE = REPO_ROOT / "tests" / "release-workflow" / "fixtures" / "r13-fixture"
ANCESTRY_REFERENCE = REPO_ROOT / "tests" / "release-workflow" / "fixtures" / "ancestry-reference"
ANCESTRY_FREQS = ANCESTRY_REFERENCE / "ref_freqs.tsv.gz"
QC_PANEL_DESCRIPTOR = REPO_ROOT / "reference-resources" / "qc-panel-hg38" / "resource.yaml"
FIXTURE_PANEL = FIXTURE / "ld-panel"
SNAKEFILE = REPO_ROOT / "workflow" / "Snakefile"
PHASE_RUNNER = REPO_ROOT / "workflow" / "phase.py"
SNAKEMAKE = shutil.which("snakemake")

sys.path.insert(0, str(REPO_ROOT))
from resources.lib.release_yaml import read_release_yaml, read_tsv  # noqa: E402

#: The pinned `opengwasdb` revision, read from pixi.toml rather than hardcoded
#: so a pin bump does not silently invalidate the completion-record assertion.
OPENGWASDB_REVISION = (
    tomllib.loads((REPO_ROOT / "pixi.toml").read_text(encoding="utf-8"))["feature"]
    ["store-build"]["pypi-dependencies"]["opengwasdb"]["rev"]
)

#: Fixture Analysis ids, in analyses.tsv order.
FIXTURE_ANALYSES = (
    "finngen-r13-BMI_FIXTURE",
    "finngen-r13-HEIGHT_FIXTURE",
    "finngen-r13-RX_STATIN_FIXTURE",
)
BMI, HEIGHT, RX_STATIN = FIXTURE_ANALYSES

#: Fixture union variant count (4 BMI + 2 new HEIGHT + 2 new RX_STATIN).
FIXTURE_VARIANTS = 8

#: The fixture's Reference-Completion child id used by the completion scenarios.
CHILD_ID = "r13-fixture-completed"

#: The tab `opengwasdb regenerate-overview` emits only when `data.zarr/rho` exists.
RHO_TAB = 'data-tab="rho"'

PHASES = (
    "validate_fixed_inputs",
    "resolve_analysis_metadata",
    "build_observed_store",
    "regenerate_observed_overview",
    "validate_observed_release",
)

n_checks = 0


def check(condition: bool, message: str) -> None:
    global n_checks
    n_checks += 1
    if not condition:
        raise AssertionError(message)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


@dataclass(frozen=True)
class Fixture:
    """One temporary copy of the fixture release, wired to a temporary artifact root."""

    release_dir: Path
    work_dir: Path
    store_dir: Path

    @property
    def build_yaml(self) -> Path:
        return self.release_dir / "build.yaml"

    @property
    def analyses(self) -> Path:
        return self.release_dir / "analyses.tsv"

    @property
    def sources(self) -> list[Path]:
        return sorted((self.release_dir / "source").glob("*.gz"))

    def completion(self, phase: str) -> Path:
        return self.work_dir / "completions" / f"{phase}.json"

    def record(self, phase: str) -> dict:
        return json.loads(self.completion(phase).read_text(encoding="utf-8"))

    def validation(self) -> dict:
        return _read_validation(self.release_dir / "validation.yaml")

    def release_status(self) -> str:
        for line in (self.release_dir / "release.yaml").read_text(encoding="utf-8").splitlines():
            if line.startswith("status:"):
                return line.split(":", 1)[1].strip()
        raise AssertionError("release.yaml has no status")

    def sidecar(self, name: str) -> Path:
        return self.release_dir / "sidecars" / name

    def store_analyses(self) -> dict[str, dict[str, str]]:
        return {row["analysis_id"]: row for row in read_tsv(self.store_dir / "analyses.tsv")}


def _read_validation(path: Path) -> dict:
    """Read the flat `validation.yaml` fields this suite asserts on."""
    fields: dict[str, str] = {}
    checks: dict[str, str] = {}
    warnings: list[str] = []
    in_checks = False
    in_warnings = False
    for line in path.read_text(encoding="utf-8").splitlines():
        if line == "checks:":
            in_checks, in_warnings = True, False
            continue
        if line.startswith("warnings:"):
            in_checks, in_warnings = False, True
            continue
        if (in_checks or in_warnings) and line and not line.startswith(" "):
            in_checks = in_warnings = False
        if in_checks and line.startswith("  "):
            key, _, value = line.strip().partition(": ")
            checks[key] = value
        elif in_warnings and line.strip().startswith("- "):
            warnings.append(line.strip()[2:].strip().strip("'\""))
        elif not in_checks and not in_warnings and line and not line.startswith(" ") and ": " in line:
            key, _, value = line.partition(": ")
            fields[key] = value
    fields["checks"] = checks
    fields["warnings"] = warnings
    return fields


@dataclass(frozen=True)
class Child:
    """One Reference-Completion child: its Release Bundle and its separate Store."""

    parent: Fixture
    release_id: str
    release_dir: Path
    store_dir: Path
    work_dir: Path

    def completion(self, phase: str) -> Path:
        return self.work_dir / "completions" / f"{phase}.json"

    def record(self, phase: str) -> dict:
        return json.loads(self.completion(phase).read_text(encoding="utf-8"))

    def sidecar(self, name: str) -> Path:
        return self.release_dir / "sidecars" / name

    @property
    def release_yaml(self) -> Path:
        return self.release_dir / "release.yaml"

    @property
    def validation(self) -> dict:
        return _read_validation(self.release_dir / "validation.yaml")

    @property
    def registration(self) -> dict:
        return read_release_yaml(self.release_yaml)


def child_of(fixture: Fixture, release_id: str = CHILD_ID) -> Child:
    """The child paths `workflow/model.py` derives from the observed release."""
    releases = fixture.work_dir.parent.parent  # <artifacts>/finngen-r13/releases
    artifact_dir = releases / release_id
    return Child(
        parent=fixture,
        release_id=release_id,
        release_dir=fixture.release_dir.parent / release_id,
        store_dir=artifact_dir / "store.opengwasdb",
        work_dir=artifact_dir / "work",
    )


def enable_rho(fixture: Fixture, *, arguments: str = "    z-thresh: 100\n    min-nulls: 1\n") -> None:
    """Turn the fixture's rho branch on with explicit opaque arguments."""
    text = fixture.build_yaml.read_text(encoding="utf-8")
    assert "rho:\n  enabled: false\n" in text, "fixture build.yaml has no rho block to enable"
    fixture.build_yaml.write_text(
        text.replace("rho:\n  enabled: false\n", f"rho:\n  enabled: true\n  arguments:\n{arguments}"),
        encoding="utf-8",
    )


def enable_completion(fixture: Fixture, release_id: str = CHILD_ID) -> None:
    """Turn the fixture's Reference-Completion branch on against the fixture panel."""
    text = fixture.build_yaml.read_text(encoding="utf-8")
    assert "reference_completion:\n  enabled: false\n" in text, "fixture build.yaml has no reference_completion block"
    block = (
        "reference_completion:\n  enabled: true\n"
        f"  family_release_id: {release_id}\n"
        "  command: complete-dense\n"
        "  arguments:\n"
        f"    ld-panel: {FIXTURE_PANEL}\n"
        "    ancestry: EUR\n"
        f"    release-id: {release_id}\n"
        "    min-cor: 0.0\n"
    )
    fixture.build_yaml.write_text(
        text.replace("reference_completion:\n  enabled: false\n", block), encoding="utf-8"
    )


def rho_group_attrs(store_dir: Path) -> dict | None:
    """The `data.zarr/rho` group's provenance attributes, or None if absent."""
    import zarr

    if not (store_dir / "data.zarr").is_dir():
        return None
    root = zarr.open_group(str(store_dir / "data.zarr"), mode="r")
    if "rho" not in root:
        return None
    return dict(root["rho"].attrs)


def store_variant_count(store_dir: Path) -> int:
    from opengwasdb.variants import VariantAxis

    axis = VariantAxis(store_dir)
    try:
        return int(axis.n_variants)
    finally:
        axis.close()


def store_fingerprint(store_dir: Path) -> str:
    """Content hash of every file in a Store, so byte-stability is checkable."""
    digest = hashlib.sha256()
    for path in sorted(item for item in store_dir.rglob("*") if item.is_file()):
        digest.update(str(path.relative_to(store_dir)).encode())
        digest.update(path.read_bytes())
    return digest.hexdigest()


def prepare(temp_root: Path, name: str) -> Fixture:
    """Copy the fixture release and point its artifact root at the temp directory."""
    scenario = temp_root / name
    shutil.rmtree(scenario, ignore_errors=True)
    release_dir = scenario / "release"
    shutil.copytree(FIXTURE, release_dir)
    artifacts = scenario / "artifacts"
    build_yaml = release_dir / "build.yaml"
    text = build_yaml.read_text(encoding="utf-8")
    assert "artifact_root: .release-work" in text, "fixture build.yaml no longer declares the repo-local root"
    build_yaml.write_text(text.replace("artifact_root: .release-work", f"artifact_root: {artifacts}"), encoding="utf-8")
    work_dir = artifacts / "finngen-r13" / "releases" / "r13-fixture" / "work"
    store_dir = work_dir.parent / "store.opengwasdb"
    return Fixture(release_dir=release_dir, work_dir=work_dir, store_dir=store_dir)


def snakemake(
    fixture: Fixture,
    *,
    until: str | None = None,
    force: str | None = None,
    dry_run: bool = False,
) -> subprocess.CompletedProcess:
    command = [
        str(SNAKEMAKE),
        "--snakefile", str(SNAKEFILE),
        "--configfile", str(fixture.build_yaml),
        "--cores", "1",
        "--printshellcmds",
    ]
    if until:
        command += ["--until", until]
    if force:
        command += ["--forcerun", force]
    if dry_run:
        command += ["--dry-run"]
    return subprocess.run(command, cwd=REPO_ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)


def planned_rules(result: subprocess.CompletedProcess) -> set[str]:
    """The rules a dry run would execute, from Snakemake's job-stats table."""
    assert_success(result, "dry run")
    return {match.group(1) for match in re.finditer(r"^(\S+)\s+\d+$", result.stdout, re.M)}


def run_phase_runner(fixture: Fixture, phase: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(PHASE_RUNNER), "--phase", phase,
         "--config", str(fixture.build_yaml), "--repo-root", str(REPO_ROOT)],
        cwd=REPO_ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
    )


def store_analysis_ids(fixture: Fixture) -> list[str]:
    return analysis_ids_of(fixture.store_dir)


def analysis_ids_of(store_dir: Path) -> list[str]:
    return [row["analysis_id"] for row in read_tsv(store_dir / "analyses.tsv")]


def rewrite_analyses(fixture: Fixture, mutate) -> None:
    fieldnames, rows = _rows(fixture.analyses)
    for row in rows:
        mutate(row)
    with fixture.analyses.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t", lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def _rows(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        return list(reader.fieldnames or []), list(reader)


def append_variant(path: Path, row: list[str]) -> None:
    """Append one FinnGen-shaped row, keeping the gzip header timestamp-free."""
    with gzip.open(path, "rt", newline="", encoding="utf-8") as handle:
        existing = list(csv.reader(handle, delimiter="\t"))
    assert existing[0] == ["#chrom", "pos", "ref", "alt", "beta", "sebeta", "af_alt", "rsids"]
    existing.append(row)
    with path.open("wb") as raw:
        with gzip.GzipFile(fileobj=raw, mode="wb", mtime=0) as compressed:
            with io.TextIOWrapper(compressed, encoding="utf-8", newline="") as writer:
                csv_writer = csv.writer(writer, delimiter="\t", lineterminator="\n")
                for line in existing:
                    csv_writer.writerow(line)


def assert_success(result: subprocess.CompletedProcess, label: str) -> None:
    if result.returncode != 0:
        raise AssertionError(f"{label} failed (exit {result.returncode}):\n{result.stdout[-4000:]}")


# ---------------------------------------------------------------------------
# Scenarios
# ---------------------------------------------------------------------------


def test_scratch_build(temp_root: Path) -> Fixture:
    """One command builds a genuine Store with real resolved metadata."""
    fixture = prepare(temp_root, "scratch")
    committed_before = sha256(fixture.analyses)
    result = snakemake(fixture)
    assert_success(result, "scratch build")

    check(fixture.store_dir.is_dir(), "the fixture Store was not built")
    manifest = json.loads((fixture.store_dir / "manifest.json").read_text(encoding="utf-8"))
    check(manifest["store_id"] == "finngen-r13", f"unexpected store_id {manifest['store_id']!r}")
    check(manifest["release_id"] == "r13-fixture", f"unexpected release_id {manifest['release_id']!r}")
    check(manifest["format_version"] == "1.0", f"unexpected store format {manifest['format_version']!r}")
    check(store_analysis_ids(fixture) == list(FIXTURE_ANALYSES), "built Store carries the wrong Analyses")
    check((fixture.store_dir / "data.zarr").is_dir(), "built Store has no data.zarr")

    # AC1: the committed analyses.tsv is read-only to the workflow.
    check(sha256(fixture.analyses) == committed_before,
          "the run mutated the committed analyses.tsv (issue #99 AC1)")

    overview = (fixture.store_dir / "overview.html").read_text(encoding="utf-8")
    check("<html>" in overview, "overview.html is not HTML")
    for analysis_id in FIXTURE_ANALYSES:
        check(analysis_id in overview, f"overview.html omits {analysis_id}")

    # AC2/AC3: derived ancestry and effect-scale metadata reach the resolved
    # file and the built Store.
    resolved = {row["analysis_id"]: row for row in read_tsv(fixture.work_dir / "analyses.resolved.tsv")}
    check(resolved[BMI]["original_sd_method"] == "estimated_from_source_maf",
          "the derived phenotype-SD method is not in the resolved file")
    check(resolved[BMI]["original_sd"], "the derived phenotype SD is not in the resolved file")
    check("ancestry_prop_EUR" in resolved[HEIGHT], "the ancestry proportions are not in the resolved file")

    store = fixture.store_analyses()
    for analysis_id in FIXTURE_ANALYSES:
        expected_scale = "log_or" if analysis_id == RX_STATIN else "sd"
        check(store[analysis_id]["assigned_ancestry"] == "EUR",
              f"{analysis_id} did not reach the Store with an assigned ancestry")
        check(store[analysis_id]["ancestry_assignment_method"] == "af_assigned",
              f"{analysis_id} did not reach the Store with af_assigned")
        check("ancestry_prop_EUR" in store[analysis_id],
              f"{analysis_id} did not reach the Store with ancestry proportions")
        check(store[analysis_id]["stored_effect_scale"] == expected_scale,
              f"{analysis_id} reached the Store with the wrong effect scale")
    check(store[BMI]["original_sd_method"] == "estimated_from_source_maf",
          "the derived phenotype-SD method did not reach the Store")
    check(store[BMI]["original_sd"], "the derived phenotype SD did not reach the Store")
    check(store[HEIGHT]["original_sd_method"] == "declared_standardised",
          "the declared-standardised method was not preserved")

    # AC4: the failed effect-scale check is recorded, and does not fail the run.
    validation = fixture.validation()
    check(validation["status"] == "failed", f"validation.yaml status is {validation['status']!r}")
    check(validation["checks"].get("store") == "passed", "the CLI store check did not pass")
    check(validation["checks"].get("files") == "passed", "the build file check did not pass")
    check(validation["checks"].get("schema") == "passed", "the schema check did not pass")
    check(validation["checks"].get("ancestry") == "passed", "the ancestry check did not pass")
    check(validation["checks"].get("effect_scale") == "failed", "the effect-scale failure was not recorded")
    check(validation["checks"].get("sd_estimation") == "failed", "the SD-estimation failure was not recorded")
    check(any(HEIGHT in warning and "effect-scale" in warning for warning in validation["warnings"]),
          "validation.yaml warnings do not name the failed effect-scale Analysis")

    # AC4: the release lands as `built`, not `validated`.
    check(fixture.release_status() == "built",
          f"a failed effect-scale check should land the release as built, got {fixture.release_status()!r}")

    # AC6: the resolution report names every Analysis whose metadata was derived.
    resolution = read_tsv(fixture.sidecar("metadata-resolution.tsv"))
    check([row["analysis_id"] for row in resolution] == list(FIXTURE_ANALYSES),
          "metadata-resolution.tsv does not cover every Analysis")
    derived = {row["analysis_id"] for row in resolution if row["derived_fields"]}
    check(derived == set(FIXTURE_ANALYSES), "the resolution report does not name every derived Analysis")
    report = {row["analysis_id"]: row for row in resolution}
    check("original_sd" in report[BMI]["derived_fields"], "BMI's derived SD is not reported")
    check(report[HEIGHT]["effect_scale_status"] == "failed", "HEIGHT's failed check is not reported")
    check(report[RX_STATIN]["effect_scale_status"] == "skipped", "the binary Analysis should be skipped")

    for phase in PHASES:
        check(fixture.completion(phase).is_file(), f"no completion record for {phase}")

    report = read_tsv(fixture.sidecar("build-report.tsv"))[0]
    check(int(report["n_analyses"]) == len(FIXTURE_ANALYSES), "build report n_analyses mismatch")
    check(int(report["n_variants"]) == FIXTURE_VARIANTS, "build report n_variants mismatch")
    check(report["status"] == "passed", "build report is not passed")
    check("/store.opengwasdb.partial " in report["command"] + " ", "build did not build into a .partial sibling")

    inputs = json.loads(fixture.sidecar("input-validation.json").read_text(encoding="utf-8"))
    check(inputs["status"] == "passed", "input-validation.json is not passed")
    check(inputs["analysis_count"] == len(FIXTURE_ANALYSES), "input-validation analysis_count mismatch")
    check(inputs["checksums_verified"] is True, "input validation did not verify checksums")
    return fixture


def test_completion_records_bind_inputs(fixture: Fixture) -> None:
    """Every record binds the fixed inputs, the revision, and the effective arguments."""
    record = fixture.record("build_observed_store")
    check(record["phase"] == "build_observed_store", "record names the wrong phase")
    check(record["store_family_id"] == "finngen-r13", "record names the wrong Store Family")
    check(record["family_release_id"] == "r13-fixture", "record names the wrong release")

    bound = record["inputs"]
    check(bound[str(fixture.build_yaml)] == sha256(fixture.build_yaml), "record does not bind build.yaml")
    check(bound[str(fixture.analyses)] == sha256(fixture.analyses), "record does not bind analyses.tsv")
    for source in fixture.sources:
        check(bound[str(source)] == sha256(source), f"record does not bind {source.name}")
    check(bound[str(QC_PANEL_DESCRIPTOR)] == sha256(QC_PANEL_DESCRIPTOR),
          "record does not bind the declared Reference Resource descriptor")

    # AC7: the ancestry reference panel used for assignment is bound, so swapping
    # the panel invalidates the resolve phase (and the build downstream of it).
    resolve_record = fixture.record("resolve_analysis_metadata")
    check(resolve_record["inputs"][str(ANCESTRY_FREQS)] == sha256(ANCESTRY_FREQS),
          "the resolve record does not bind the ancestry reference panel")
    check(resolve_record["validation"]["effect_scale"] == "failed",
          "the resolve record does not carry the effect-scale result")
    check(resolve_record["validation"]["derived_analysis_count"] == len(FIXTURE_ANALYSES),
          "the resolve record does not name every derived Analysis")

    check(record["opengwasdb"]["revision"] == OPENGWASDB_REVISION, "record binds the wrong opengwasdb revision")
    check(record["opengwasdb"]["version"], "record binds no opengwasdb version")
    check("--store-id" in record["command"] and "finngen-r13" in record["command"], "effective arguments are not recorded")
    check(record["command"][1] == "build-dense-vcf", f"record names command {record['command'][1]!r}")
    check(str(fixture.store_dir / "manifest.json") in record["outputs"], "record does not name the Store envelope output")
    check(record["completed_at"].endswith("+00:00"), "record has no UTC completion time")
    check(record["validation"]["status"] == "passed", "record does not carry the read-back result")
    check(record["input_fingerprint"], "record has no input fingerprint")

    overview = fixture.record("regenerate_observed_overview")
    check(overview["command"][1] == "regenerate-overview", "overview phase did not call regenerate-overview")
    check(str(fixture.store_dir / "overview.html") in overview["outputs"], "overview record does not name overview.html")
    check(overview["validation"]["overview_sha256"] == sha256(fixture.store_dir / "overview.html"),
          "overview record does not bind the regenerated page")

    validate = fixture.record("validate_observed_release")
    check(validate["command"][1] == "validate", "validate phase did not call opengwasdb validate")
    check(str(fixture.release_dir / "validation.yaml") in validate["outputs"], "validate record does not name validation.yaml")
    check(validate["validation"]["release_status"] == "built", "validate record does not land the built status")


def test_reference_panel_invalidates_phases(fixture: Fixture) -> None:
    """Editing a declared Reference Resource invalidates the phases that bind it.

    The QC-panel descriptor and the ancestry reference panel are repository files
    (not part of the fixture copy), so each edit is a temporary content change
    restored in a `finally`. The dry run only plans -- it never executes a phase
    -- so the modified panel is never read, and restoring it makes the DAG a
    no-op again.
    """
    descriptor = QC_PANEL_DESCRIPTOR
    original = descriptor.read_bytes()
    stat = descriptor.stat()
    try:
        descriptor.write_bytes(original + b"# workflow-invalidation probe\n")
        planned = planned_rules(snakemake(fixture, dry_run=True))
        check("validate_fixed_inputs" in planned,
              "editing a declared Reference Resource descriptor did not invalidate validate_fixed_inputs")
        check("resolve_analysis_metadata" in planned,
              "editing a declared Reference Resource descriptor did not invalidate resolve_analysis_metadata")
    finally:
        descriptor.write_bytes(original)
        os.utime(descriptor, (stat.st_atime, stat.st_mtime))
    check(descriptor.read_bytes() == original, "the Reference Resource descriptor was not restored")
    check("validate_fixed_inputs" not in planned_rules(snakemake(fixture, dry_run=True)),
          "the restored descriptor still invalidates validate_fixed_inputs")

    reference = ANCESTRY_FREQS
    original = reference.read_bytes()
    stat = reference.stat()
    try:
        reference.write_bytes(original + b"\n")
        planned = planned_rules(snakemake(fixture, dry_run=True))
        check("resolve_analysis_metadata" in planned,
              "swapping the ancestry reference panel did not invalidate resolve_analysis_metadata")
    finally:
        reference.write_bytes(original)
        os.utime(reference, (stat.st_atime, stat.st_mtime))
    check(reference.read_bytes() == original, "the ancestry reference panel was not restored")


def test_completed_rerun_is_noop(fixture: Fixture) -> None:
    """Rerunning a fully completed build re-executes no phase."""
    before = {phase: sha256(fixture.completion(phase)) for phase in PHASES}
    resolved_before = sha256(fixture.work_dir / "analyses.resolved.tsv")
    result = snakemake(fixture)
    assert_success(result, "no-op rerun")
    check("Nothing to be done" in result.stdout, "the DAG did not report itself up to date")
    check(all(sha256(fixture.completion(phase)) == digest for phase, digest in before.items()),
          "a rerun rewrote a completion record")
    check(sha256(fixture.work_dir / "analyses.resolved.tsv") == resolved_before,
          "a rerun rewrote the resolved table")


def test_interrupted_run_resumes(temp_root: Path) -> Fixture:
    """Stopping before the build leaves no Store and resumes without redoing resolve."""
    fixture = prepare(temp_root, "interrupted")
    result = snakemake(fixture, until="resolve_analysis_metadata")
    assert_success(result, "interrupted run")
    check(fixture.completion("resolve_analysis_metadata").is_file(), "resolve did not complete")
    check(not fixture.completion("build_observed_store").exists(), "build completed despite --until resolve")
    check(not fixture.store_dir.exists(), "a Store exists before the build phase ran")

    resolve_hash = sha256(fixture.completion("resolve_analysis_metadata"))
    result = snakemake(fixture)
    assert_success(result, "resume run")
    check(fixture.completion("build_observed_store").is_file(), "resume did not build the Store")
    check(fixture.validation()["checks"].get("store") == "passed", "resumed release did not validate")
    check(sha256(fixture.completion("resolve_analysis_metadata")) == resolve_hash,
          "resume re-ran the already-complete resolve phase")
    return fixture


def test_partial_store_cannot_masquerade(fixture: Fixture) -> None:
    """A partial Store with no completion record is rebuilt, not trusted.

    This is what an interrupted build leaves behind: the completed phases keep
    their records, the build and everything after it have none, and the Store
    path holds whatever the killed process had written. The rerun must descend
    into the missing phases and replace the partial Store.
    """
    resolve_hash = sha256(fixture.completion("resolve_analysis_metadata"))

    for phase in ("build_observed_store", "regenerate_observed_overview", "validate_observed_release"):
        fixture.completion(phase).unlink()
    (fixture.store_dir / "manifest.json").unlink()
    (fixture.store_dir / "PARTIAL").write_text("interrupted build\n", encoding="utf-8")

    result = snakemake(fixture)
    assert_success(result, "partial-store rerun")
    check(not (fixture.store_dir / "PARTIAL").exists(), "the partial Store survived the rerun")
    check((fixture.store_dir / "manifest.json").is_file(), "the rerun did not rebuild the Store envelope")
    check(store_analysis_ids(fixture) == list(FIXTURE_ANALYSES), "the rebuilt Store carries the wrong Analyses")
    check(fixture.validation()["checks"].get("store") == "passed", "the rebuilt Store did not validate")
    check(sha256(fixture.completion("resolve_analysis_metadata")) == resolve_hash,
          "the rerun re-ran the already-complete resolve phase")
    check(not fixture.store_dir.with_name(fixture.store_dir.name + ".partial").exists(),
          "the build left its .partial sibling behind")


def test_edits_invalidate_and_flow_through(fixture: Fixture) -> None:
    """Editing build.yaml, analyses.tsv, or a source file invalidates the affected phases.

    Each edit is checked with a dry run -- the DAG Snakemake would execute --
    and then one real run proves all three edits actually reach the Store.
    """
    before_build = sha256(fixture.completion("build_observed_store"))

    fixture.build_yaml.write_text(
        fixture.build_yaml.read_text(encoding="utf-8").replace("n-workers: 1", "n-workers: 2"),
        encoding="utf-8",
    )
    check("build_observed_store" in planned_rules(snakemake(fixture, dry_run=True)),
          "editing build.yaml did not invalidate the build phase")

    rewrite_analyses(fixture, lambda row: row.update(
        {"analysis_label": "Edited body mass index"} if row["analysis_id"] == BMI else {}
    ))
    check("resolve_analysis_metadata" in planned_rules(snakemake(fixture, dry_run=True)),
          "editing analyses.tsv did not invalidate the resolve phase")

    edited_source = fixture.release_dir / "source" / "finngen_R13_BMI_FIXTURE.gz"
    append_variant(edited_source, ["8", "9000000", "A", "C", "0.04", "0.02", "0.37", "rs9"])
    new_checksum = sha256(edited_source)
    rewrite_analyses(fixture, lambda row: row.update(
        {"checksum": new_checksum} if row["analysis_id"] == BMI else {}
    ))
    check("build_observed_store" in planned_rules(snakemake(fixture, dry_run=True)),
          "editing a source file did not invalidate the build phase")

    result = snakemake(fixture)
    assert_success(result, "edited inputs rerun")
    check(sha256(fixture.completion("build_observed_store")) != before_build,
          "the edited inputs did not re-run the build")
    labels = {row["analysis_id"]: row["analysis_label"] for row in read_tsv(fixture.store_dir / "analyses.tsv")}
    check(labels[BMI] == "Edited body mass index", "the edited label did not reach the Store")
    report = read_tsv(fixture.sidecar("build-report.tsv"))[0]
    check(int(report["n_variants"]) == FIXTURE_VARIANTS + 1, "the new source variant did not reach the Store")
    command = fixture.record("build_observed_store")["command"]
    check("--n-workers" in command and "2" in command, "the edited build argument did not reach the CLI")
    check(fixture.validation()["checks"].get("store") == "passed", "the release did not validate after the edits")


def test_effect_scale_escalation_blocks(temp_root: Path) -> None:
    """`effect_scale_validation.block_on_failure` escalates the failure to blocking."""
    fixture = prepare(temp_root, "escalate")
    text = fixture.build_yaml.read_text(encoding="utf-8")
    check("block_on_failure: no" in text, "the fixture build.yaml no longer declares the escalation key off")
    fixture.build_yaml.write_text(text.replace("block_on_failure: no", "block_on_failure: yes"), encoding="utf-8")

    validate = run_phase_runner(fixture, "validate_fixed_inputs")
    assert_success(validate, "escalation fixture validate")
    resolve = run_phase_runner(fixture, "resolve_analysis_metadata")
    check(resolve.returncode != 0, "effect-scale escalation did not block the resolve phase")
    check("block_on_failure" in resolve.stdout, "the block does not name the escalation key")
    check(HEIGHT in resolve.stdout, "the block does not name the failing Analysis")
    check(not fixture.completion("build_observed_store").exists(), "the build ran despite the escalation")


def test_file_name_source_column(temp_root: Path) -> None:
    """analyses.tsv may name its source column `file_name` instead of `source_file`.

    `resources/lib/release_plan.py` and `workflow/model.py` both accept either
    name. The resolve phase must resolve `file_name` the same way, or the shared
    builder manifest points at the source directory rather than each file.
    """
    fixture = prepare(temp_root, "file-name-column")
    lines = fixture.analyses.read_text(encoding="utf-8").splitlines()
    header = lines[0].split("\t")
    header[header.index("source_file")] = "file_name"
    lines[0] = "\t".join(header)
    fixture.analyses.write_text("\n".join(lines) + "\n", encoding="utf-8")

    result = snakemake(fixture)
    assert_success(result, "file_name source column build")
    check(store_analysis_ids(fixture) == list(FIXTURE_ANALYSES),
          "the file_name-column release built the wrong Analyses")
    # The resolved table persists the absolute usable path under the canonical
    # `source_file` name even though the fixed input spelled it `file_name`.
    resolved = read_tsv(fixture.work_dir / "analyses.resolved.tsv")
    check(resolved and all("source_file" in row for row in resolved),
          "the resolved table dropped source_file for a file_name-column release")
    for row in resolved:
        source = Path(row["source_file"])
        check(source.is_absolute(), f"resolved source_file {row['source_file']!r} is not absolute")
        check(source.is_file(), f"resolved source_file {row['source_file']!r} is not a source file")
    manifest = read_tsv(fixture.work_dir / "builder-manifest.tsv")
    check(len(manifest) == len(FIXTURE_ANALYSES), "builder manifest row count mismatch")
    for row in manifest:
        file_path = Path(row["file_path"])
        check(file_path.is_absolute(), f"builder manifest file_path {row['file_path']!r} is not absolute")
        check(file_path.is_file(), f"builder manifest file_path {row['file_path']!r} is not a source file")


def test_snakefile_is_wiring_only() -> None:
    """The Snakefile names no Store Family, no column, and no Store Layout."""
    text = SNAKEFILE.read_text(encoding="utf-8")
    forbidden = (
        "finngen", "analysis_id", "source_file", "analysis_label", "source_genome_build",
        "source_reader_capability", "trait_id", "trait_name", "file_path", "stored_effect_scale",
        "original_sd_method", "sample_size",
        "dense", "hybrid", "ragged",
    )
    for token in forbidden:
        check(token not in text, f"the Snakefile contains {token!r}")
    check("phase.py" in text, "the Snakefile does not delegate to the phase runner")


def test_rho_disabled_skips_rho(fixture: Fixture) -> None:
    """With rho disabled the workflow skips it and still regenerates the overview."""
    check(not fixture.completion("build_observed_rho").exists(), "rho ran though it is disabled")
    check(rho_group_attrs(fixture.store_dir) is None, "the Store carries a rho group though rho is disabled")
    html = (fixture.store_dir / "overview.html").read_text(encoding="utf-8")
    check(RHO_TAB not in html, "the overview has a Rho tab though rho is disabled")
    check(fixture.record("regenerate_observed_overview")["validation"]["rho_tab"] is False,
          "the overview record claims a Rho tab though rho is disabled")


def test_rho_enabled_builds_then_regenerates(temp_root: Path) -> Fixture:
    """With rho enabled the Store gains rho in place and the overview is regenerated after it."""
    fixture = prepare(temp_root, "rho-enabled")
    enable_rho(fixture)
    result = snakemake(fixture)
    assert_success(result, "rho-enabled build")

    attrs = rho_group_attrs(fixture.store_dir)
    check(attrs is not None, "the rho-enabled build left no data.zarr/rho group")
    check(attrs.get("method"), "the rho group records no method")
    check(attrs.get("n_analyses") == len(FIXTURE_ANALYSES),
          f"the rho group covers {attrs.get('n_analyses')} Analyses, expected {len(FIXTURE_ANALYSES)}")

    rho_record = fixture.record("build_observed_rho")
    check(rho_record["command"][1] == "build-dense-rho", "rho did not call build-dense-rho")
    check(str(fixture.completion("build_observed_store")) in rho_record["inputs"],
          "rho does not depend on the build phase")
    check(str(fixture.store_dir) == rho_record["store_uri"], "rho mutated a Store other than the observed one")

    overview_record = fixture.record("regenerate_observed_overview")
    check(overview_record["command"][1] == "regenerate-overview",
          "the overview was not produced by regenerate-overview")
    check(str(fixture.completion("build_observed_rho")) in overview_record["inputs"],
          "the overview does not depend on rho, so it could be regenerated before rho ran")
    check(overview_record["validation"]["rho_tab"] is True, "the overview record does not record the Rho tab")

    html = (fixture.store_dir / "overview.html").read_text(encoding="utf-8")
    check(RHO_TAB in html, "the regenerated overview reflects no post-rho Store (no Rho tab)")
    check(fixture.validation()["checks"].get("store") == "passed",
          "the rho-enabled release did not validate its Store")
    return fixture


def test_rho_on_non_dense_refused(temp_root: Path) -> None:
    """A non-Dense layout asking for rho is refused at input validation, naming the layout."""
    fixture = prepare(temp_root, "rho-non-dense")
    text = fixture.build_yaml.read_text(encoding="utf-8")
    text = text.replace("store_layout: dense-observed", "store_layout: hybrid-observed")
    text = text.replace("rho:\n  enabled: false\n", "rho:\n  enabled: true\n")
    fixture.build_yaml.write_text(text, encoding="utf-8")

    result = run_phase_runner(fixture, "validate_fixed_inputs")
    check(result.returncode != 0, "rho on a non-Dense layout was not refused at input validation")
    check("rho.enabled" in result.stdout, f"the refusal does not name rho.enabled:\n{result.stdout}")
    check("hybrid-observed" in result.stdout, f"the refusal does not name the layout:\n{result.stdout}")
    check("Dense-only" in result.stdout, f"the refusal does not say rho is Dense-only:\n{result.stdout}")
    check(not fixture.work_dir.exists(), "Store work began before the non-Dense rho refusal")

    result = snakemake(fixture)
    check(result.returncode != 0, "the DAG ran a non-Dense rho release")
    check(not fixture.store_dir.exists(), "a Store was built for a non-Dense rho release")


def assert_completion_tail(child: Child, *, rho: bool) -> None:
    """The child runs the same tail as the parent: rho, overview, validation, in order."""
    register = child.record("register_completed_release")
    complete = child.record("complete_store")
    check(str(child.parent.completion("validate_observed_release")) in register["inputs"],
          "child registration does not depend on the observed validation")
    check(str(child.completion("register_completed_release")) in complete["inputs"],
          "the completion does not depend on the registration")
    check(complete["family_release_id"] == child.release_id,
          f"the completion record names release {complete['family_release_id']!r}, expected {child.release_id!r}")
    check(complete["store_uri"] == str(child.store_dir),
          "the completion record does not name the child Store")

    if rho:
        rho_record = child.record("build_completed_rho")
        check(rho_record["command"][1] == "build-dense-rho", "the child rho did not call build-dense-rho")
        check(str(child.completion("complete_store")) in rho_record["inputs"],
              "the child rho does not depend on the completion")
        overview_upstream = str(child.completion("build_completed_rho"))
    else:
        overview_upstream = str(child.completion("complete_store"))
    overview = child.record("regenerate_completed_overview")
    check(overview_upstream in overview["inputs"],
          "the child overview does not depend on the child's last mutation")
    check(overview["command"][1] == "regenerate-overview",
          "the child overview was not produced by regenerate-overview")
    validate = child.record("validate_completed_release")
    check(str(child.completion("regenerate_completed_overview")) in validate["inputs"],
          "the child validation does not depend on the child overview")
    check(validate["command"][1] == "validate", "the child was not validated")


def test_reference_completion_builds_child(temp_root: Path) -> tuple[Fixture, Child]:
    """Reference Completion registers a lineage-linked child and builds a separate Store."""
    fixture = prepare(temp_root, "completion")
    enable_rho(fixture)
    enable_completion(fixture)
    child = child_of(fixture)

    result = snakemake(fixture, until="validate_observed_release")
    assert_success(result, "observed tail before completion")
    observed_before = store_fingerprint(fixture.store_dir)

    result = snakemake(fixture)
    assert_success(result, "completion build")

    check(child.release_yaml.is_file(), "the child Store Release was not registered")
    registration = child.registration
    check(registration.get("family_release_id") == CHILD_ID,
          f"the registered child names release {registration.get('family_release_id')!r}")
    check((registration.get("lineage") or {}).get("derived_from") == "r13-fixture",
          "the registered child's lineage does not name the observed parent")
    check(child.release_dir.parent == fixture.release_dir.parent,
          "the child Release Bundle is not a sibling of the observed one")

    check(store_fingerprint(fixture.store_dir) == observed_before,
          "the completion branch mutated the observed parent Store")

    check(child.store_dir.is_dir(), "no separate child Store was built")
    check(child.store_dir != fixture.store_dir, "the child Store is the observed Store")
    manifest = json.loads((child.store_dir / "manifest.json").read_text(encoding="utf-8"))
    check(manifest["release_id"] == CHILD_ID, f"the child Store release_id is {manifest['release_id']!r}")
    check(manifest["completion_state"] == "reference_completed",
          f"the child Store completion_state is {manifest['completion_state']!r}")
    check(analysis_ids_of(child.store_dir) == list(FIXTURE_ANALYSES), "the child Store carries the wrong Analyses")
    check(store_variant_count(child.store_dir) > FIXTURE_VARIANTS,
          "the child Store's variant axis was not widened by the reference panel")

    assert_completion_tail(child, rho=True)

    child_html = (child.store_dir / "overview.html").read_text(encoding="utf-8")
    check(RHO_TAB in child_html, "the child overview has no Rho tab")
    check(child.validation["status"] == "passed", "the child Store did not validate")
    return fixture, child


def interrupt_completion(fixture: Fixture) -> None:
    """Run the completion phase and kill it once opengwasdb has checkpointed.

    This leaves exactly what an interrupted completion leaves: a checkpoint
    directory and the phase's own resume marker, but no child Store at its own
    path and no completion record. The whole process group is killed so the
    spawned `opengwasdb complete-dense` dies with the phase runner rather than
    finishing in the background.
    """
    child = child_of(fixture)
    partial = child.store_dir.with_name(child.store_dir.name + ".partial")
    build_params = partial.parent / f".{partial.name}.checkpoint" / "build_params.json"
    process = subprocess.Popen(
        [sys.executable, str(PHASE_RUNNER), "--phase", "complete_store",
         "--config", str(fixture.build_yaml), "--repo-root", str(REPO_ROOT)],
        cwd=REPO_ROOT, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True,
        start_new_session=True,
    )
    killed = False
    try:
        deadline = time.time() + 60
        while time.time() < deadline:
            if build_params.is_file():
                try:
                    json.loads(build_params.read_text(encoding="utf-8"))
                except ValueError:
                    time.sleep(0.005)
                    continue
                os.killpg(os.getpgid(process.pid), signal.SIGKILL)
                killed = True
                break
            if process.poll() is not None:
                break
            time.sleep(0.005)
    finally:
        if not killed and process.poll() is None:
            os.killpg(os.getpgid(process.pid), signal.SIGKILL)
    output = process.communicate()[0]
    check(killed, f"the completion finished before it could be interrupted:\n{output[-2000:]}")


def test_completion_interrupted_resumes(temp_root: Path) -> tuple[Fixture, Child]:
    """An interrupted completion resumes rather than treating the partial child as complete."""
    fixture = prepare(temp_root, "completion-interrupted")
    enable_rho(fixture)
    enable_completion(fixture)
    child = child_of(fixture)

    result = snakemake(fixture, until="validate_observed_release")
    assert_success(result, "observed tail before completion")
    observed_before = store_fingerprint(fixture.store_dir)

    interrupt_completion(fixture)
    partial = child.store_dir.with_name(child.store_dir.name + ".partial")
    checkpoint = partial.parent / f".{partial.name}.checkpoint"
    check(checkpoint.is_dir(), "the interrupted completion left no checkpoint directory")
    check(not child.completion("complete_store").exists(), "an interrupted completion wrote a record")
    check(not child.store_dir.exists(), "an interrupted completion left a Store at the child's own path")

    result = snakemake(fixture)
    assert_success(result, "resumed completion")
    record = child.record("complete_store")
    check(record["command"][1] == "complete-dense-resume",
          f"the rerun did not resume the interrupted completion (ran {record['command'][1]!r})")
    check(record["validation"]["resumed"] is True, "the completion record does not mark the run resumed")
    check(child.store_dir.is_dir(), "the resumed completion left no child Store")
    check(child.validation["status"] == "passed", "the resumed child did not validate")
    check(store_fingerprint(fixture.store_dir) == observed_before,
          "the resumed completion mutated the observed parent Store")
    return fixture, child


def test_partial_child_cannot_masquerade(fixture: Fixture, child: Child) -> None:
    """A partial child Store with no record is rebuilt, not trusted."""
    observed_before = store_fingerprint(fixture.store_dir)
    for phase in (
        "complete_store",
        "build_completed_rho",
        "regenerate_completed_overview",
        "validate_completed_release",
    ):
        child.completion(phase).unlink()
    (child.store_dir / "manifest.json").unlink()
    (child.store_dir / "PARTIAL").write_text("interrupted completion\n", encoding="utf-8")

    result = snakemake(fixture)
    assert_success(result, "partial-child rerun")
    check(not (child.store_dir / "PARTIAL").exists(), "the partial child Store survived the rerun")
    check((child.store_dir / "manifest.json").is_file(), "the rerun did not rebuild the child envelope")
    check(child.validation["status"] == "passed", "the rebuilt child did not validate")
    check(child.record("register_completed_release")["family_release_id"] == CHILD_ID,
          "the rerun re-registered a different child")
    check(store_fingerprint(fixture.store_dir) == observed_before,
          "the child rebuild mutated the observed parent Store")


def test_hand_written_overview_is_replaced(fixture: Fixture) -> None:
    """overview.html is generated from Store data, not hand-written."""
    overview = fixture.store_dir / "overview.html"
    expected = overview.read_bytes()
    before = sha256(fixture.completion("validate_observed_release"))
    overview.write_text("hand-written overview\n", encoding="utf-8")

    result = snakemake(fixture, force="regenerate_observed_overview")
    assert_success(result, "overview regeneration")
    check(overview.read_bytes() == expected, "the hand-written overview was not replaced by the regenerated one")
    check(fixture.record("regenerate_observed_overview")["command"][1] == "regenerate-overview",
          "the overview was not produced by regenerate-overview")
    check(sha256(fixture.completion("validate_observed_release")) != before,
          "validation did not re-run downstream of the regeneration")


def main() -> int:
    if SNAKEMAKE is None:
        print(
            "snakemake is not on PATH; run this suite via `pixi run test` (or --environment workflow)",
            file=sys.stderr,
        )
        return 2
    with tempfile.TemporaryDirectory(prefix="release-workflow-") as temp:
        temp_root = Path(temp)
        fixture = test_scratch_build(temp_root)
        test_completion_records_bind_inputs(fixture)
        test_reference_panel_invalidates_phases(fixture)
        test_completed_rerun_is_noop(fixture)
        test_hand_written_overview_is_replaced(fixture)
        test_edits_invalidate_and_flow_through(fixture)
        test_file_name_source_column(temp_root)
        test_effect_scale_escalation_blocks(temp_root)
        test_snakefile_is_wiring_only()
        test_rho_disabled_skips_rho(fixture)
        test_rho_enabled_builds_then_regenerates(temp_root)
        test_rho_on_non_dense_refused(temp_root)
        test_reference_completion_builds_child(temp_root)
        test_partial_child_cannot_masquerade(
            *test_completion_interrupted_resumes(temp_root)
        )
        test_partial_store_cannot_masquerade(test_interrupted_run_resumes(temp_root))
    print(f"release-workflow: {n_checks} checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
