store_id: OGS-00002
layout: ragged
completion_state: reference_completed
complete:
  command: complete-ragged
  options:
    ld-panel: /data/opengwasdb/reference/hgdp1kgp-hg38/panel
    ancestry: EUR
post:
  top_hits: false
  rho: false
  overview: false
  validate: true
